### ISSUE TITLE
Abstract is included three times in dc and etdms

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/fcrepo4-oaiprovider#12]
For items like https://era.library.ualberta.ca/files/cp5547r50s , the abstract field is presented in triplicate in the OAI records 

- dc: https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:era.library.ualberta.ca:1/cp5547r50s
- etdms: https://era.library.ualberta.ca/oai?verb=GetRecord&identifier=oai:era.library.ualberta.ca:1/cp5547r50s&metadataPrefix=oai_etdms

It should be presented only once. It shows up correctly in the original record, when accessed in the app interface or in rails console or directly in Fedora.

**Comment by jefferya** [comment]
Intermittent issue - doesn't occur on all objects. Looking for a commonality in the Fedora objects.

Inspecting Fedora objects found `dcterms:abstract` is sometimes type `String` and other times `Binary` when looking a `fcr:export?format=jcr/xml&skipBinary=false` for a specific object. The the type is `Binary`, the `dcterms:abstract` property has not one but three values (all appear to be same). 

If the type is `Binary`, three abstracts are added to the OAI-Provider output. The `jcr/xml` for an example `Binary` object:

```
<sv:property sv:name="dcterms:abstract" sv:type="Binary" sv:multiple="true">
  <sv:value>U29saWQgb3hpZ...</sv:value>
  <sv:value>U29saWQgb3hpZ...</sv:value>
  <sv:value>U29saWQgb3hpZ...</sv:value>
</sv:property>
```

If the type is `String`, only one abstract in the OAI-Provider output. The `jcr/xml` for an example `String` object:

```
<sv:property sv:name="dcterms:abstract" sv:type="String" sv:multiple="true">
  <sv:value>The recognition.... </sv:value>
</sv:property>
```

Why is the `Binary` typed `dcterms:abstract` only appearing once on the Fedora REST interface? Or the ERA interface?

Options:
* Alter OAI-Provider to squash duplicate `sv:value` within a given `sv:property`? Is there ever a time duplicates might be needed?
* Bug in thesis handling? Or Fedora 4.2?

Code references:
* https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/master/src/main/java/org/fcrepo/oai/generator/JcrOaiDcGenerator.java#L403-L412
* https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/master/src/main/java/org/fcrepo/oai/generator/JcrOaiDcGenerator.java#L194-L196
*https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/master/src/main/java/org/fcrepo/oai/generator/JcrOaiEtdmsGenerator.java#L216-L219

Reference objects:
* Binary
  * cp/55/47/r5/cp5547r50s/fcr:export?format=jcr/xml&skipBinary=false
* String
  * 44/55/8d/46/44558d463/fcr:export?format=jcr/xml

Examples from sample of 300 records (8) instances where `abstract` in triplicate:
<identifier>oai:era.library.ualberta.ca:1/cdj52w493n</identifier>
<identifier>oai:era.library.ualberta.ca:1/c5712m6776</identifier>
<identifier>oai:era.library.ualberta.ca:1/c5m60qs065</identifier>
<identifier>oai:era.library.ualberta.ca:1/c5m60qs08s</identifier>
<identifier>oai:era.library.ualberta.ca:1/c02870w05q</identifier>
<identifier>oai:era.library.ualberta.ca:1/c0r967401n</identifier>
<identifier>oai:era.library.ualberta.ca:1/c0z708w60t</identifier>
<identifier>oai:era.library.ualberta.ca:1/cdn39x1716</identifier>
