### ISSUE TITLE
Not all sets are included in ListSets response

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/fcrepo4-oaiprovider#15]
https://era.library.ualberta.ca/oai?verb=ListSets returns a list of sets with no continuation token, but not all of ERA's collections and communities are included. In particular, the Theses and Dissertations collection (setspec 44558t416) is absent.

**Comment by jefferya** [comment]
Working notes:
* maxListSize set to 300. Number of sets returned is 186 in era.library.ualberta.ca therefor no resumption token in response
* checking query that produces results - logic looks ok at first glance
* found some weirdness between objects that appear and those that don't, inspecting further:

* missing object:
```
<sv:property sv:name="ualidentifier:is_official" sv:type="String" sv:multiple="true">
<sv:value>true</sv:value>
</sv:property>
```
  
* present object:
```
<sv:property sv:name="ualidentifier:is_official" sv:type="String" sv:multiple="true">
<sv:value xsi:type="xs:base64Binary">dHJ1ZRheXhhodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSNib29sZWFu</sv:value>
</sv:property>
```

**Comment by jefferya** [comment]
Possible solutions to the binary/string data:

1) remove `is_official` property from the query
2) add "or" logic to the query such as:
 .append(" AND (col.[ualidentifier:is_official] = CAST('" + booleanTrue + "' AS BINARY)")
 .append(" OR (col.[ualidentifier:is_official] = 'true') ")

Code segment:
https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/master/src/main/java/org/fcrepo/oai/service/OAIProviderService.java#L782
