### ISSUE TITLE
ORE: atom:author is sometimes repeated

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/fcrepo4-oaiprovider#18]
If both  `dcterms:creator` and `marcrel:dis` are present then atom:author is repeated.

@zschoenb should I only use `marcrel:dis` to map to atom:author? Or privilege `marcrel:dis` and only use `dcterms:creator` if `marcrel:dis` is absent?

Example with both:
* https://era-test.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=ore&identifier=oai%3Aera.library.ualberta.ca%3A1%2F6969z174h

Example with only `marcrel:dis`:
* https://era-test.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=ore&identifier=oai%3Aera.library.ualberta.ca%3A1%2Fp5547t785

**Comment by zschoenb** [comment]
Exactly. privilege marcrel:dis and only use dcterms:creator if marcrel:dis is absent? in both cases, however, publish these as dcterms:creator in the ORE record
