### ISSUE TITLE
ORE: add both dcterms:rights and dcterms:license

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/fcrepo4-oaiprovider#19]
```
On Thu, Aug 3, 2017 at 11:48 AM, Zachary Schoenberger <zschoenb@ualberta.ca> wrote:
....
We should probably have both dcterm:rights and dcterm:license both present, each mapped respectively. Sometimes there is no license, other times there is no rights, but there is always at least one, and most of the time there is both. I think it makes more sense to do it this way.
````

@zschoenb what would the output look like if both are present? Would the output be a second `rdf:Description` block? Also, do you have an example handy?

Fyi: Current logic, use one or the other but not both (privileging `dcterms:rights` 
``` 
if `dcterms:rights` then output
else if `dcterms:license` then output
```

**Comment by zschoenb** [comment]
it should be in the one rdf:Description block, just add both a rights node and a license node. should be fine. The ORE spec says add all the triples you want :)

`				
<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://era.library.ualberta.ca/files/c8g84mm44k/ore.xml">
<rdf:type rdf:resource="http://fedora.info/definitions/v4/repository#Resource" />
<dcterms:modified>2014-04-29T15:32:59.800Z</dcterms:modified> 
<dcterms:rights>The rights of this work are governed by a Creative Commons Attribution NC-ND-By 3.0 license"\</dcterms:rights> 
<dcterms:license>Creative Commons Attribution-Non-Commercial-No Derivatives 3.0 Unported</dcterms:license> 
<dcterms:isVersionOf>some citation</dcterms:isVersionOf> 
</rdf:Description>`

**Comment by zschoenb** [comment]
I caught this myself recently. We aren't sure exactly why, but in many cases marcrel:dis has been duplicated in dc:creator. Give primacy to marcrel:dis. If it isn't present, take dc:creator.

**Comment by jefferya** [comment]
Example for reference: oai:era.library.ualberta.ca:1/cp5547r50s
