### ISSUE TITLE
Change to query-required date arguments

### ISSUE THREAD

**Issue by anayram** [ualbertalib/fcrepo4-oaiprovider#44]
To match LAC expected query parameters we need to set the provider to accept date arguments with no specified time.

For instance, set the provider to accept the following query:
https://era.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_etdms&from=2017-06-26
where date is year-month-day (yyyy-mm-dd) without hours-minutes-seconds (Thh:mm:ssZ).

When I test the provider against LAC's validator I get the error:

> Critical Error
> The specified set does not exist for this repository.
> https://era.library.ualberta.ca/oai

which is due to our provider requiring full date-time parameters.

**Comment by jefferya** [comment]
ref. http://www.openarchives.org/OAI/openarchivesprotocol.html#SelectiveHarvestingandDatestamps

Also addresses:

REQUEST: http://localhost:8080/fcrepo/rest/oai?verb=ListRecords&metadataPrefix=oai_dc&from=2002-02-05&until=2002-02-06T05:35:00Z GET

FAIL:    Error code badArgument not found in response but should be given to the request: verb=ListRecords&metadataPrefix=oai_dc&from=2002-02-05&until=2002-02-06T05:35:00Z The request has different granularities for the from and until parameters.
