### ISSUE TITLE
Set-based selective requests not working

### ISSUE THREAD

**Issue by anayram** [ualbertalib/fcrepo4-oaiprovider#49]
When trying to get records limited by collection, `Set` constructs are not working. Selective harvesting does work with other parameters like `from` or `until`, so the problem seems to be limited to `Set`.

If LAC tries to harvest only theses and dissertations in DublinCore format, they will get many other records that are not part of the Theses and Dissertations collection.

Because requests with `metadataPrefix=oai_etdms` output only theses and dissertations, I can't be sure if this bug is exclusive to requests with `metadataPrefix=oai_dc`.

To reproduce:
https://era.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&Set=db9a4e71-f809-4385-a274-048f28eb6814:f42f3da6-00c3-4581-b785-63725c33c7ce
or
http://gillingham2.library.ualberta.ca:8080/fedora/rest/oai?verb=ListRecords&metadataPrefix=oai_dc&Set=db9a4e71-f809-4385-a274-048f28eb6814:f42f3da6-00c3-4581-b785-63725c33c7ce

**Comment by piyapongch** [comment]
@anayram @weiweishi @pbinkley @jefferya: I have looked at the OAI provider source codes. It seems to be correct. It queries filter on predicate http://terms.library.ualberta.ca/identifiers/hasCollectionId for the set parameter. If we have not changed the predicate for hasCollectionId, the result should be correct.

I will schedule the Fedora re-indexing when it is possible. Then, we can try it again.

**Comment by anayram** [comment]
@piyapongch thank you. Seems like set-based harvesting is not working yet.

If LAC is not collecting DC metadata anymore (only ETD-MS) then we don't need to fix this just now for their harvesting since ETD-MS only outputs theses. @weiweishi do you know if this has been confirmed with LAC or is is there a way we can contact them to check whether or not they need DC?

Still this might be something to fix later.

**Comment by weiweishi** [comment]
Thanks @anayram I have not heard back from LAC yet but will contact them to confirm re:DC metadata. @ConnorSheremeta is going to compare output from Fedora vs output from post-fedora OAISys. So I am tagging him so that he's aware.

**Comment by sfarnel** [comment]
Thanks @weiweishi It would be great if Connor and Mariana can work together on the comparison of data

**Comment by jefferya** [comment]
@anayram 
In the original example, is `set` (with lowercase s) the correct property? The original example uses an uppercase - sorry for not catching this in July.

https://era.library.ualberta.ca/oai?verb=ListIdentifiers&metadataPrefix=oai_dc&set=5a69bd79-86e9-4208-82d9-917c95873ed5:384e12b4-4427-43fc-9689-33d8eef979db

**Comment by anayram** [comment]
@jefferya yes! Thank you this is great news. Sorry for the confusion. Closing this ticket.
